### ISSUE TITLE
miniswarm logs <service> does not work

### ISSUE THREAD

**Issue by batwicket** [aelsabbahy/miniswarm#2]
Using docker 1.12.1-beta24 (build 11525) and the quickstart on OSX El Capitan. I know you don't have a Mac - it may be a docker issue. 

This returns nothing. Passing '-f' just blocks waiting for something.
`miniswarm logs app`

I believe you are issuing:
`docker logs  "app.1.8iatypaea8ii8lv78pjzxklf5"`

When i run this at the command prompt i get:
`Error: No such container: app.1.8iatypaea8ii8lv78pjzxklf5`

**Comment by aelsabbahy** [comment]
Is this happening consistently or intermittently?

What does `docker service ps app` say?

**Comment by batwicket** [comment]
hmm.. just tried it and `docker service ps app` says that the app is running.
Also tried 
`miniswarm logs app`
and this time it did return an entry. Seems to be intermittent or perhaps i need to increase the verbosity of the log. Will keep an eye on it to see if there is something specific i can pin down for you.

**Comment by aelsabbahy** [comment]
I think this happens when a service is started, but not actually launched yet (ex. images still downloading).

Let me know if your experience differs, or if you find constant misbehavior.

**Comment by aelsabbahy** [comment]
This feature will most likely go away once docker/docker#24812 is implemented (possibly 1.13).

**Comment by batwicket** [comment]
ok - thanks for this utility.
